#!/bin/bash
set +x +e
TOOLS_PATH=$(pwd)
SOURCE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo Build ecosconfig tools for eCos.
sudo apt-get install -y gcc g++ tcl-dev tk-dev
BUILD_TMP_PATH=$(mktemp -d)
pushd $BUILD_TMP_PATH \
&& $SOURCE_PATH/host/configure && make && mv ./tools/configtool/standalone/common/ecosconfig $TOOLS_PATH \
&& popd && rm -rf $BUILD_TMP_PATH

if command -v $TOOLS_PATH/ecosconfig >/dev/null 2>&1 && $(pwd)/ecosconfig --version >/dev/null 2>&1;
then
echo Build ecosconfig sucessful! Please move $(pwd)/ecosconfig to you PATH.
else
echo Build ecosconfig failed.
exit -1
fi
